# https://taskfile.dev

version: '3'

tasks:
    tag:minor:
        desc: Add git tag, but upgrade latest minor version
        cmds:
          - git tag -a "$(git tag | tail -1 | cut -d'.' -f1).$(($(git tag | tail -1 | cut -d'.' -f2)+1))" -m  "$(git tag | tail -1 | cut -d'.' -f1).$(($(git tag | tail -1 | cut -d'.' -f2)+1))"

    tag:major:
        desc: Add git tag, upgrade latest major version
        cmds:
          - git tag -a "v$(($(git tag | tail -1 | cut -d'.' -f1 | cut -d'v' -f2)+1)).0" -m  "v$(($(git tag | tail -1 | cut -d'.' -f1 | cut -d'v' -f2)+1)).0"
    
    push:tags:
        desc: Push git tags to origin
        cmds:
          - git push origin --tags