# https://taskfile.dev

version: '3'

tasks:

    build:
      desc: Build binary locally
      cmds:
        - cmd: go build
          silent: true

    git:tag:minor:
      desc: Add git tag, but upgrade latest minor version
      cmds:
        - cmd: git tag -a "$(git tag | sort -V | tail -1 | cut -d'.' -f1).$(($(git tag | sort -V | tail -1 | cut -d'.' -f2)+1))" -m  "$(git tag | sort -V | tail -1 | cut -d'.' -f1).$(($(git tag | sort -V | tail -1 | cut -d'.' -f2)+1))"
          silent: true

    git:tag:major:
      desc: Add git tag, upgrade latest major version
      cmds:
        - cmd: git tag -a "v$(($(git tag | sort -V | tail -1 | cut -d'.' -f1 | cut -d'v' -f2)+1)).0" -m  "v$(($(git tag | sort -V | tail -1 | cut -d'.' -f1 | cut -d'v' -f2)+1)).0"
          silent: true
    
    git:tag:deletelatest:
      desc: Delete latest (local) tag
      cmds:
        - cmd: git tag -d $(git tag | sort -V | tail -1)
          silent: true

    release:minor:
      desc: Create new minor version tag and push
      cmds:
        - task: git:tag:minor
        - cmd: git push --follow-tags
          silent: true

    release:major:
      desc: Create new major version tag and push
      cmds:
        - task: git:tag:major
        - cmd: git push --follow-tags
          silent: true
