name: Release tags

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            See [https://github.com/${{ github.repository }}/blob/${{ github.ref }}/CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.ref }}/CHANGELOG.md) for more information on what has changed.
          draft: false
          prerelease: false
      
      - name: Compile binaries for windows
        shell: bash
        run: env GOOS=windows GOARCH=amd64 go build -o ./spell.exe main.go
      - name: Compile binaries for linux
        shell: bash
        run: env GOOS=linux GOARCH=amd64 go build -o ./spell main.go

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          hub release edit -a ./spell -a ./spell.exe -m "" "$tag_name"
